<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<Compile Remove="TraineeScreeningTool.WinForms\**" />
		<None Remove="TraineeScreeningTool.WinForms\**" />
		<Content Remove="TraineeScreeningTool.WinForms\**" />
		<EmbeddedResource Remove="TraineeScreeningTool.WinForms\**" />
	</ItemGroup>
	
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

</Project>
